/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { NameToken, NameTokenInterface } from "../../contracts/NameToken";

const _abi = [
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060e88061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806354fd4d5014602d575b600080fd5b604080518082018252600f81526e6e616d65746f6b656e2d302e302e3160881b60208201529051605c91906065565b60405180910390f35b60006020808352835180602085015260005b818110156091578581018301518582016040015282016077565b506000604082860101526040601f19601f830116850101925050509291505056fea264697066735822122083f47f55681fcc325b219fb88e4689ec1f588d53b3c3d8431c2291d9bc2e038864736f6c63430008180033";

type NameTokenConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NameTokenConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NameToken__factory extends ContractFactory {
  constructor(...args: NameTokenConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      NameToken & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): NameToken__factory {
    return super.connect(runner) as NameToken__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NameTokenInterface {
    return new Interface(_abi) as NameTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): NameToken {
    return new Contract(address, _abi, runner) as unknown as NameToken;
  }
}
