/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { AuctionHouse, AuctionHouseInterface } from "../AuctionHouse";

const _abi = [
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060eb8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806354fd4d5014602d575b600080fd5b604080518082018252601281527161756374696f6e686f7573652d302e302e3160701b60208201529051605f91906068565b60405180910390f35b60006020808352835180602085015260005b81811015609457858101830151858201604001528201607a565b506000604082860101526040601f19601f830116850101925050509291505056fea2646970667358221220ea53b345a521834e381779ff75b74b0f854ae9a1882eff93aca08052b6d5801764736f6c63430008180033";

type AuctionHouseConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AuctionHouseConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AuctionHouse__factory extends ContractFactory {
  constructor(...args: AuctionHouseConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AuctionHouse & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AuctionHouse__factory {
    return super.connect(runner) as AuctionHouse__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AuctionHouseInterface {
    return new Interface(_abi) as AuctionHouseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AuctionHouse {
    return new Contract(address, _abi, runner) as unknown as AuctionHouse;
  }
}
