/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAuctionHouse__factory } from "./IAuctionHouse__factory";
export { IRegistry__factory } from "./IRegistry__factory";
