/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAuctionHouseInterface extends Interface {
  getFunction(
    nameOrSignature: "commitBid" | "finalizeAuction" | "revealBid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AuctionFinalized" | "BidCommitted" | "BidRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commitBid",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAuction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revealBid",
    values: [string, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "commitBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealBid", data: BytesLike): Result;
}

export namespace AuctionFinalizedEvent {
  export type InputTuple = [
    namehash: BytesLike,
    winner: AddressLike,
    winningBid: BigNumberish
  ];
  export type OutputTuple = [
    namehash: string,
    winner: string,
    winningBid: bigint
  ];
  export interface OutputObject {
    namehash: string;
    winner: string;
    winningBid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidCommittedEvent {
  export type InputTuple = [namehash: BytesLike, bidder: AddressLike];
  export type OutputTuple = [namehash: string, bidder: string];
  export interface OutputObject {
    namehash: string;
    bidder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidRevealedEvent {
  export type InputTuple = [
    namehash: BytesLike,
    bidder: AddressLike,
    bidAmount: BigNumberish
  ];
  export type OutputTuple = [
    namehash: string,
    bidder: string,
    bidAmount: bigint
  ];
  export interface OutputObject {
    namehash: string;
    bidder: string;
    bidAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAuctionHouse extends BaseContract {
  connect(runner?: ContractRunner | null): IAuctionHouse;
  waitForDeployment(): Promise<this>;

  interface: IAuctionHouseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitBid: TypedContractMethod<
    [namehash: BytesLike, bidHash: BytesLike],
    [void],
    "nonpayable"
  >;

  finalizeAuction: TypedContractMethod<[name: string], [void], "nonpayable">;

  revealBid: TypedContractMethod<
    [name: string, bidAmount: BigNumberish, salt: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitBid"
  ): TypedContractMethod<
    [namehash: BytesLike, bidHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeAuction"
  ): TypedContractMethod<[name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealBid"
  ): TypedContractMethod<
    [name: string, bidAmount: BigNumberish, salt: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuctionFinalized"
  ): TypedContractEvent<
    AuctionFinalizedEvent.InputTuple,
    AuctionFinalizedEvent.OutputTuple,
    AuctionFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "BidCommitted"
  ): TypedContractEvent<
    BidCommittedEvent.InputTuple,
    BidCommittedEvent.OutputTuple,
    BidCommittedEvent.OutputObject
  >;
  getEvent(
    key: "BidRevealed"
  ): TypedContractEvent<
    BidRevealedEvent.InputTuple,
    BidRevealedEvent.OutputTuple,
    BidRevealedEvent.OutputObject
  >;

  filters: {
    "AuctionFinalized(bytes32,address,uint256)": TypedContractEvent<
      AuctionFinalizedEvent.InputTuple,
      AuctionFinalizedEvent.OutputTuple,
      AuctionFinalizedEvent.OutputObject
    >;
    AuctionFinalized: TypedContractEvent<
      AuctionFinalizedEvent.InputTuple,
      AuctionFinalizedEvent.OutputTuple,
      AuctionFinalizedEvent.OutputObject
    >;

    "BidCommitted(bytes32,address)": TypedContractEvent<
      BidCommittedEvent.InputTuple,
      BidCommittedEvent.OutputTuple,
      BidCommittedEvent.OutputObject
    >;
    BidCommitted: TypedContractEvent<
      BidCommittedEvent.InputTuple,
      BidCommittedEvent.OutputTuple,
      BidCommittedEvent.OutputObject
    >;

    "BidRevealed(bytes32,address,uint256)": TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;
    BidRevealed: TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;
  };
}
