/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AuctionHouseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auctionEnd"
      | "beneficiary"
      | "commitBid"
      | "duration"
      | "finalizeAuction"
      | "getCommit"
      | "getCommitTime"
      | "getDeposit"
      | "getHighestBid"
      | "getHighestBidder"
      | "isFinalized"
      | "proceeds"
      | "registry"
      | "reservePrice"
      | "revealBid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AuctionFinalized" | "BidCommitted" | "BidRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auctionEnd",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitBid",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "duration", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizeAuction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommit",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitTime",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHighestBid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHighestBidder",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFinalized",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "proceeds", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reservePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealBid",
    values: [string, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "auctionEnd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "beneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commitBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "duration", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCommit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCommitTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHighestBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHighestBidder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proceeds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reservePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealBid", data: BytesLike): Result;
}

export namespace AuctionFinalizedEvent {
  export type InputTuple = [
    namehash: BytesLike,
    winner: AddressLike,
    winningBid: BigNumberish
  ];
  export type OutputTuple = [
    namehash: string,
    winner: string,
    winningBid: bigint
  ];
  export interface OutputObject {
    namehash: string;
    winner: string;
    winningBid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidCommittedEvent {
  export type InputTuple = [namehash: BytesLike, bidder: AddressLike];
  export type OutputTuple = [namehash: string, bidder: string];
  export interface OutputObject {
    namehash: string;
    bidder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidRevealedEvent {
  export type InputTuple = [
    namehash: BytesLike,
    bidder: AddressLike,
    bidAmount: BigNumberish
  ];
  export type OutputTuple = [
    namehash: string,
    bidder: string,
    bidAmount: bigint
  ];
  export interface OutputObject {
    namehash: string;
    bidder: string;
    bidAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuctionHouse extends BaseContract {
  connect(runner?: ContractRunner | null): AuctionHouse;
  waitForDeployment(): Promise<this>;

  interface: AuctionHouseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auctionEnd: TypedContractMethod<[namehash: BytesLike], [bigint], "view">;

  beneficiary: TypedContractMethod<[], [string], "view">;

  commitBid: TypedContractMethod<
    [namehash: BytesLike, bidHash: BytesLike],
    [void],
    "payable"
  >;

  duration: TypedContractMethod<[], [bigint], "view">;

  finalizeAuction: TypedContractMethod<[name: string], [void], "nonpayable">;

  getCommit: TypedContractMethod<
    [namehash: BytesLike, bidder: AddressLike],
    [string],
    "view"
  >;

  getCommitTime: TypedContractMethod<
    [namehash: BytesLike, bidder: AddressLike],
    [bigint],
    "view"
  >;

  getDeposit: TypedContractMethod<
    [namehash: BytesLike, bidder: AddressLike],
    [bigint],
    "view"
  >;

  getHighestBid: TypedContractMethod<[namehash: BytesLike], [bigint], "view">;

  getHighestBidder: TypedContractMethod<
    [namehash: BytesLike],
    [string],
    "view"
  >;

  isFinalized: TypedContractMethod<[namehash: BytesLike], [boolean], "view">;

  proceeds: TypedContractMethod<[], [bigint], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  reservePrice: TypedContractMethod<[], [bigint], "view">;

  revealBid: TypedContractMethod<
    [name: string, bidAmount: BigNumberish, salt: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auctionEnd"
  ): TypedContractMethod<[namehash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "beneficiary"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "commitBid"
  ): TypedContractMethod<
    [namehash: BytesLike, bidHash: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "duration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeAuction"
  ): TypedContractMethod<[name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCommit"
  ): TypedContractMethod<
    [namehash: BytesLike, bidder: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCommitTime"
  ): TypedContractMethod<
    [namehash: BytesLike, bidder: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<
    [namehash: BytesLike, bidder: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHighestBid"
  ): TypedContractMethod<[namehash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHighestBidder"
  ): TypedContractMethod<[namehash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isFinalized"
  ): TypedContractMethod<[namehash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proceeds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reservePrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealBid"
  ): TypedContractMethod<
    [name: string, bidAmount: BigNumberish, salt: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuctionFinalized"
  ): TypedContractEvent<
    AuctionFinalizedEvent.InputTuple,
    AuctionFinalizedEvent.OutputTuple,
    AuctionFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "BidCommitted"
  ): TypedContractEvent<
    BidCommittedEvent.InputTuple,
    BidCommittedEvent.OutputTuple,
    BidCommittedEvent.OutputObject
  >;
  getEvent(
    key: "BidRevealed"
  ): TypedContractEvent<
    BidRevealedEvent.InputTuple,
    BidRevealedEvent.OutputTuple,
    BidRevealedEvent.OutputObject
  >;

  filters: {
    "AuctionFinalized(bytes32,address,uint256)": TypedContractEvent<
      AuctionFinalizedEvent.InputTuple,
      AuctionFinalizedEvent.OutputTuple,
      AuctionFinalizedEvent.OutputObject
    >;
    AuctionFinalized: TypedContractEvent<
      AuctionFinalizedEvent.InputTuple,
      AuctionFinalizedEvent.OutputTuple,
      AuctionFinalizedEvent.OutputObject
    >;

    "BidCommitted(bytes32,address)": TypedContractEvent<
      BidCommittedEvent.InputTuple,
      BidCommittedEvent.OutputTuple,
      BidCommittedEvent.OutputObject
    >;
    BidCommitted: TypedContractEvent<
      BidCommittedEvent.InputTuple,
      BidCommittedEvent.OutputTuple,
      BidCommittedEvent.OutputObject
    >;

    "BidRevealed(bytes32,address,uint256)": TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;
    BidRevealed: TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;
  };
}
